"""schema_motorista_cpfcnh_update

Revision ID: 5cea726bb8ae
Revises: 26429dd84828
Create Date: 2025-05-28 17:57:42.871839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cea726bb8ae'
down_revision: Union[str, None] = '26429dd84828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
